### ISSUE TITLE
Gamecrash wenn hooking and sticking to an enderman

### ISSUE THREAD

**Issue by SattesKrokodil** [CammiePone/Hookshot#12]
https://pastebin.com/MKRtuAwy

**Comment by CammiePone** [comment]
Can't replicate. I noticed that part of it has to do with another mod's `healAlliesDamage()` being called from a mixin.

I also noticed you have AdventureZ and MobZ installed, both of which are prolifically buggy. See if you can replicate without either of those installed. If you can, my suggestion is to do a binary test.

Basically just remove have of the mods from the mods folder, and test with that half. If the bug still occurs, remove half of the ones that are still there. If it doesn't occur, swap the half out with the other half, and repeat until you find the mod responsible.

**Comment by SattesKrokodil** [comment]
I am stupid I tested it in the wrong instance. It's another mod that causes this issue, ill test later today which one it is. Thanks for your response and awesome update!
