### ISSUE TITLE
Recipe doesn't exist on 1.17.1 server

### ISSUE THREAD

**Issue by walshyb** [CammiePone/Hookshot#19]
All the recipes for changing the color of the hookshot and the recipes for upgrading / repairing are there, but the one to create the og one is not there

**Comment by CammiePone** [comment]
Okay but I'm gonna need a bit more information than that. Is this a dedicated server or singleplayer? What mods do you have installed? All that fun stuff.

I should really get around to making an issue template.

**Comment by walshyb** [comment]
Hello! Sorry I shouldn't given that info from the get.

- Server: Multiplayer server running 1.17.1 on GCP
- Mods installed: I'm using the modpack [Another Quality Modpack 2](https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2)
- Mod loader: Fabric
- I don't see anything related 

Let me know if there's any other info you need!

**Comment by CammiePone** [comment]
What's GCP?

**Comment by walshyb** [comment]
Google Cloud Platform! Running my own server on a google compute instance. This shouldn't matter too much though

**Comment by CammiePone** [comment]
Ahh, okay. Well, with just Hookshot in a dedicated server, there's no issues with the recipes, so if I had to guess maybe the modpack you're using makes some alteration? You could ask the modpack devs and find out if that's the case, but this isn't a base Hookshot issue as far as I can tell.
