### ISSUE TITLE
1.19.3 Compatibility

### ISSUE THREAD

**Issue by ghost** [CammiePone/Hookshot#36]
I forked your mod in order to port it to 1.19.3 for personal use. 
Because of the switch to JOML API, I wasn't able to make the chain rendering work, so I simply commented that part out.
Obviously I couldn't PR such an unfinished job, but I wanted to let you know that it's there in case you ever started to work on a 1.19.3 update.

**Comment by CammiePone** [comment]
oh I was actually planning on porting everything to 1.19.3 today. I can do Hookshot before the others if you want

**Comment by ghost** [comment]
Actually I've just checked what you did with your minecart mod and finally fixed the chain renderer. I'll PR it soon so you can doublecheck.

**Comment by CammiePone** [comment]
alright thank you! saves me a lotta time, so I really appreciate it
