### ISSUE TITLE
Hookshot that pulls entities towards you

### ISSUE THREAD

**Issue by CammiePone** [CammiePone/Hookshot#4]
One that pulls entities towards you instead of you to blocks

**Comment by Lv44EnderShaman** [comment]
I'm very glad someone submitted this request. I'm willing to back it as I had about the same idea that I remarked on in a Reddit thread.

**Comment by CammiePone** [comment]
I may still add this one, but I've gone ahead and made it so that the hookshot will now pull you towards entities.

**Comment by CammiePone** [comment]
Hookshot now pulls entities towards you if you crouch
